### ISSUE TITLE
레시피 리스트 카드 크기 다른 문제

### ISSUE THREAD

**Issue by hellonayeon** [hellonayeon/recipe-recommend-service#12]
![image](https://user-images.githubusercontent.com/43202607/134766267-29c558ab-cf37-4029-9f66-25ca1f804487.png)

사진처럼 **레시피 별로 카드 크기가 다른데**, 크기를 일관되게 맞추면 좋겠어요!

**[예상 원인]**
1. 레시피 사진별 크기 차이
2. 레시피 관련한 내용량(레시피 이름, 요약설명 등)의 차이

**Comment by KKHoon210417** [comment]
#14 이슈에서 댓글 달았듯 다른 카드 레이아웃으로 변경해보겠습니다.
아마 글씨 줄이 달라서 발생하는 현상같은데 레이아웃 너비,높이 사이즈를 제한해서 해결해보겠습니다.
