### ISSUE TITLE
카드 생기는 순서

### ISSUE THREAD

**Issue by hellonayeon** [hellonayeon/recipe-recommend-service#14]
실습할때도 의아하다고 느꼈던 부분인데... 카드가 열을 다 안채우고 다음 행으로 넘어가서 그려지는 이유가 뭘까요...
부트스트랩 레이아웃 관련된 부분인지 원인을 모르겠네요. 이유를 아시는분... 설명해주시면 감사하겠습니다 😭

![image](https://user-images.githubusercontent.com/43202607/134772368-5fa0545c-11bf-427a-a794-7fae25a543cb.png)
![image](https://user-images.githubusercontent.com/43202607/134772449-ceb1099e-6c27-42c9-a7e1-b913f6252f77.png)

**Comment by KKHoon210417** [comment]
제가 해볼게요.
card-columns 자체가 열먼저 채우도록 설정된거같아요.
card-columns를 다른 카드종류로 바꾼 다음 추가로 고정 너비와 높이를 css먹여줘야 할것 같습니다.
<해결 방안?>
- [ ] 부트스트랩 card-columns -> card-deck 로 변경
- [ ] card-deck의 경우 행이 안바뀌기 때문에 최소,최대 너비 제한하여 강제로 행 바뀌도록 설정
