### ISSUE TITLE
DB에서 Front Page로 재료항목 넘겨받기

### ISSUE THREAD

**Issue by profoundsea25** [hellonayeon/recipe-recommend-service#19]
DB의 재료 항목들을 Front Page 재료 선택 스크롤로 가져오고 선택되는 것까지 하는 작업입니다.

**Comment by profoundsea25** [comment]
리스트에 불러오기는 성공했습니다.
할 일

- [ ] 선택된 재료 표시하기
- [ ] 3개 이상일 경우 선택한 재표 / 선택될 재료 추가 표시

**Comment by hellonayeon** [comment]
해준님!! 선택지 보여주는 방식을 바꿀까 하는데 어떨까요?? #18 코멘트 한번만 읽어주시면 감사하겠습니다!

**Comment by hellonayeon** [comment]
선택된 재료 광훈님한테 넘겨주는 부분까지 해주시면, 제가 새로운 선택지 방식으로 페이지랑 선택재료 표시 부분 수정하겠습니다.

**Comment by profoundsea25** [comment]
지금 커밋된 버전으로 테스트 한 번 해보세요. 재료 선택 조건을 1개로 낮춘 상태입니다.
불러오는 데이터가 많으면 레시피 추천리스트에서 항목을 불러오는데 몇 초 정도 걸릴 수 있습니다.
