### ISSUE TITLE
연산 속도 개선 / 검색 결과 없음 알림 / 로딩 페이지

### ISSUE THREAD

**Issue by profoundsea25** [hellonayeon/recipe-recommend-service#30]
내일(09/28) 오전 중으로 마칠 것으로 예상됩니다!
연산 속도 개선은 검색해보니까 나연님이 말씀 해주신대로 집합 자료형 연산으로 바꾸면 개선될 것 같아요.

- [x] 연산 속도 개선
- [x] 검색 결과 없음 알림
- [x] 로딩 페이지

**Comment by profoundsea25** [comment]
검색이 더 정확해짐과 동시에 더 느려졌습니다.
로딩 페이지와 검색 결과가 없을 경우에 대한 알림창 코딩 중입니다.<br><br><br>


### **_reference : 더 느려진 이유가 궁금하신 분들을 위해_**

검색 방식을 바꾸는 이유는 "연산 속도" 때문이었습니다. 그러나 결과적으로 더 느려졌습니다. 그런데도 수정을 하는 이유는 **기존 방식의 검색 결과가 정확하지 않음**을 발견했기 때문입니다.

![image](https://user-images.githubusercontent.com/86033506/135186224-97f14417-cb5e-4b95-826b-7b12fc63e30f.png)

첨부된 이미지에서 드래그 된 자료를 보시면 아시겠지만, 같은 RECIPE_ID가 292임에도 불구하고, 하나는 부재료에 간장이, 하나는 양념에 간장이 각기 다른 양으로 저장되어 있습니다.
요점은 "**같은 재료가 다른 양으로 2번 이상 기록된 레시피가 존재한다.**" 입니다. (제가 발견한 케이스만 해도 11개입니다.)

기존 방식의(이하 count방식) 문제점을 예를 들어 설명하면 다음과 같습니다. 우리가 첫 페이지에서 [간장, 쌀, 소금]을 선택했다고 합시다. (일단 다른 조건은 고려하지 맙시다.) 검색 결과 판별은 3가지 재료를 선택했으니, 코드에서 count 변수가 3이 되면 옳은 검색 결과라고 판별합니다. 대조할 레시피의 재료는 다음과 같다고 합시다.

레시피A = [**간장**, **쌀**, **소금**, 안심, 콩나물] 
레시피B = [**간장**, **쌀**, 다진마늘, 다진파, **간장**]
레시피C = [**간장**, **간장**, **간장**]
레시피D = [**간장,** **쌀**, **소금**, 후추, **간장**]

우리의 목적은 레시피A, 레시피D만을 검색 결과로 가져오는 것입니다. 그러나 기존 방식의 검색을 실행하게 되면, 레시피 D를 제외한 **A, B, C를 검색 결과로** 가져옵니다. 이유는 각 레시피에 대한 count 변수 값에 있습니다.

레시피A : count = 3
레시피B : count = 3
레시피C : count = 3
레시피D : count = 4

기존의 방식으로 검색할 경우 중복되는 재료에 대한 검사를 하지 않기 때문에, 컴퓨터가 연산할 때는 간장이 1번 나오든 2번 나오든 어쨌든 우리가 선택한 재료 안에 포함되므로 그때마다 count가 됩니다. 따라서 간장만 3번 나와도 컴퓨터는 "옳은 검색 결과"라고 판별합니다.

다행히 우리의 새로운 방식(이하 차집합 방식)은 이러한 중복되는 재료를 걸러 **보다 정확한 검색을 가능**하게 합니다. 문제는 기존보다 상황에 따라 훨씬 **느려진다**는 겁니다.

[선택 재료 '간장', 한식, 나머지 모두 체크] 로 검색 시 걸리는 연산 시간은 다음과 같습니다.
count 방식 : 1.7959137000000016 (약 **1.78~1.80** 초) / 검색 결과 **137개**
차집합 방식 : 7.4863389 (약 **7.4~7.6** 초) / 검색 결과 **142개**

한편, [선택 재료 '간장, 소금, 쌀', 한식, 나머지 모두 체크] 로 검색 시 걸리는 연산 시간은 다음과 같습니다.
count 방식 ; 1.769222499999998 (약 **1.75~1.77** 초) / 검색 결과 **8개** 
차집합 방식 : 7.483455599999999 (약 **7.4~7.6** 초) / 검색 결과 **1개**

저도 연산을 하면서 새로운 방식이 어떨 때는 1초에 가까운 연산 시간을 보일 때도 있습니다. 사용자 환경에 따라 기존 방식보다 영향을 많이 받는 것 같습니다. 중요한 점은, **더 정확하지만 대부분의 상황에서 더 느려진다는 겁니다.**
배포할 때 EC2 환경은 제 컴퓨터보다 클린할테니 어떻게 될지는 모르지만... 일단 더 정확한 검색에 초점을 두고 있습니다.

**Comment by profoundsea25** [comment]
새로운 검색 방식에 대한 소스코드입니다.
https://github.com/hellonayeon/recipe-recommend-service/blob/ca57c258b5df8cd2054dfc3a5853ac882377642a/app.py#L75-L81

개선의 여지가 많아보입니다. 시간 나시면 한 번 리뷰해주시고 의견 있으시면 언제든 게더/슬랙/코멘트 주세요

**Comment by profoundsea25** [comment]
아니 왜 갑자기 빨라짐?

**Comment by HWON0720** [comment]
현재 로딩 페이지 코딩 중입니다. 새로운 파일로 생성하면 출력이 되는데, 저희 index.html에 적용하면 출력이 되지 않아 아직 방법을 찾고 있습니다. 찾아놓은 몇 개 더 적용해보고 해결되지 않으면 말씀드리겠습니다! 😂
