### ISSUE TITLE
자동완성 검색창 기능

### ISSUE THREAD

**Issue by KKHoon210417** [hellonayeon/recipe-recommend-service#33]
JQUERY에 .autocomplete를 사용해서 검색창에 재료를 입력해서 선택할 수 있는 기능을 추가하겠습니다.

**Comment by profoundsea25** [comment]
늦었지만... 참고하실만한 링크 하나 남길게요
https://offbyone.tistory.com/260

**Comment by hellonayeon** [comment]
저도 확인해볼게요 ~~

**Comment by KKHoon210417** [comment]
추가로
아래 코드 사용하게 되면
list({v['IRDNT_NM']: v for v in research_list}.values())

'IRDN_NM'에 중복되는 value를 제거할 수 있어욥

**Comment by KKHoon210417** [comment]
링크 참조 :
https://programmer93.tistory.com/2

**Comment by profoundsea25** [comment]
- [ ] 재료 선택시 input 창 초기화

**Comment by KKHoon210417** [comment]
재료 선택시 input 창
close 매소드를 이용해 해결

**Comment by KKHoon210417** [comment]
자동완성기능 수정 완료
 
1. source json으로 받을 시 자동완성 안되는 문제.
- [ ] API로 받은 재료 리스트를 script 내에 변수에 배열을 저장하여 source로 이용하여 문제 해결완료
- [ ] 주재료, 부재료, 양념 구분 삭제 재료로 통일

2. 셀렉트와 인풋박스 통일성 문제
- [ ] 인풋 박스와 통일
