### ISSUE TITLE
좋아요 기능

### ISSUE THREAD

**Issue by HWON0720** [hellonayeon/recipe-recommend-service#4]
**1. 좋아요(=즐겨찾기) 리스트**
1) "좋아요" 레시피 리스트, GET, /receipe/like, {}, 좋아요된 레시피 리스트
- 레시피 이름, 재료, 이미지, ..., 좋아요 개수(cnt = 1)

**2. 좋아요 선택, 취소**
1) 좋아요 선택
- PUT, /recipe/like {"recipe": {"아이디", "이름", "분류"}},
1-1) 좋아요 선택 시, 레시피 저장
- 레시피 저장, POST, /recipe, {"recipe": {"아이디", "이름", "분류"}}, 완료 메시지

2) 좋아요 취소
- PUT, /recipe/unlike {"recipe": {"아이디", "이름", "분류"}},

**Comment by profoundsea25** [comment]
제가 해보겠습니다 :)

**Comment by profoundsea25** [comment]
_**to be fixed (1) 210925**_

- [ ] 문제 1) '검색 리스트 페이지'에서는 좋아요 - 좋아요 해제가 정상 작동하나, '상세 페이지'나 '좋아요 탭'에서는 좋아요 - 좋아요 해제가 정상 작동하지 않는 점

  1. 다른 url마다 좋아요-좋아요 해제 관련 PUT 함수를 새로 만드는 것 (총 4개를 더 만들어야 함, 가장 쉬운 방법)
  2. switch문을 활용해 해결해보는 방법 (need to try)

- [ ] 문제 2) 좋아요된 항목들이 새로고침 할 때마다 초기화 되는 점 (DB에는 좋아요 수가 정상적으로 남음), 메인 - 상세 - 좋아요 페이지 모두 점검해야 함

**Comment by profoundsea25** [comment]
to be fixed (2) 210925

- [ ] 문제 1) 좋아요 관련 논의 : 좋아요를 어떤 방향으로?

**Comment by hellonayeon** [comment]
1. 추후에 로그인을 통해 사용자 관리를 한다면 DB에 사용자(db.user)에 대한 정보들을 가지고 있을테니, USER_ID & RECIPE_ID 기반으로 중복 좋아요에 대한 문제가 해결되지 않을까 싶네요. 지금 단계에서는 나중에 사용자 관리를 하게됐을때 코드 수정이 용이하도록 지금처럼 그 부분을 염두하시면서 코딩하면 나중에 확장시키기 편할 것 같아요!

2. 수정사항이 생기면(예를들어 새로운 댓글을 작성하는 행위) 새로운 데이터를 DB에 저장 후, 전체 댓글들을 가져와서 다시 그리도록 요청합니다! 저는 현재 이 방법으로 해결했지만 아무래도 모든 데이터를 가져와 다시 그린다는게 데이터량이 많아지면 부담되니까 개별적으로 append 하는 법도 좋을 것 같아요! 새로운 데이터에 대한 출력은 같이 고민해봐요 😆

DB 초기화 다시 할때마다 번거로웠는데 덕분에 편리해졌네요!! 고생많으셨습니다 👍
