### ISSUE TITLE
프론트엔드 수정(부트스트랩)

### ISSUE THREAD

**Issue by KKHoon210417** [hellonayeon/recipe-recommend-service#44]
프론트엔드 수정(페이지 분할)

- [x] 부트스트랩 웹 양식 구매 진행

- [x] index.html 프론트엔드 페이지 분할

- [x] 부트스트랩 웹 양식 페이지 적용

**Comment by hellonayeon** [comment]
index.html 오류 수정하신 분 마이크 켜고 즉시 알려주시길!!! 🤣

**Comment by KKHoon210417** [comment]
이번 이슈는 닫습니다.
