### ISSUE TITLE
좋아요 기능 수정

### ISSUE THREAD

**Issue by hellonayeon** [hellonayeon/recipe-recommend-service#56]
이제 로그인을 통해 사용자를 관리할 수 있으므로 좋아요 기능 수정이 필요합니다.

** 사용자 별 `좋아요` 1회씩만 가능하게 구현 **

* `likes` 컬렉션 생성
* `RECIPE_ID` `USERNAME` `TYPE` 필드 생성

** 구현 방법 **
API
1. 좋아요 선택: 도큐먼트 추가
2. 좋아요 해제: 도큐먼트 삭제
3. 1-2의 결과로 나온 컬렉션 도큐먼트 총 개수 리턴

**Comment by profoundsea25** [comment]
기능에 대한 구현은 다 되었고 feature/56 브랜치에 올려두었습니다. 

다만, 전에 말씀하신대로 검색한 리스트(추천탭)과 좋아요 탭 간 코드의 유사성이 있어 처리 중에 있습니다. 비교할 곳은 js에서 2 곳, app.py에서 1곳이고 비교 사진은 다음과 같습니다.

**1. 검색 불러오기 vs 좋아요 불러오기**
![1 검색 불러오기 vs 좋아요 불러오기](https://user-images.githubusercontent.com/86033506/136648549-e4c4ecbd-5d28-4982-a8d7-97e37b509c2a.png)

하이라이트 되지 않은 곳이 똑같은 부분입니다. 보시다시피 변수 선언 쪽에서 중복되나 POST와 GET의 차이, 예외 처리의 차이가 있어 이 부분은 건드리지 않으려고 합니다. 다만 makeRecipeList와 makeRecipeLikedLikst는 2번째 사진에서 보듯 거의 비슷하기 때문에 둘을 구별하는 인수를 주고 함수를 통일하려고 합니다.

**2. 검색 리스트 만들기 vs 좋아요 리스트 만들기**
![2 검색 리스트 만들기 vs 좋아요 리스트 만들기](https://user-images.githubusercontent.com/86033506/136648554-90a89611-c93d-4cae-ada4-b8c5680b3af3.png)

전에 팀장님께서 말씀해주신대로 가장 비슷한 부분입니다. 함수명과 뒤에 좋아요 부분, 그리고 이것들이 HTML에 붙여지는 위치(id)만 다르고, 다른 부분은 다 같습니다. 위에서 말한 듯 함수를 어디에서 호출하였는지를 구별하는 인수를 하나 추가하고, 그 인수를 활용한 조건문으로 함수를 하나로 합칠 수 있을 것입니다.

**3. 검색 API vs 좋아요 API**
![3 검색 API vs 좋아요 API](https://user-images.githubusercontent.com/86033506/136648563-d719ab84-dc84-4cb6-9572-3c94e5a44542.png)

마지막은 app.py 부분인데, 뒷 부분만 같고 중간 부분만 달라서 이 함수의 method = ['GET', 'POST'] (확실하지 않으나 예전에 이렇게 처리한 것을 본 적이 있어 검색해보려고 합니다.) 로 묶고, 중간에 DB에서 data_we_want를 뽑아오는 부분을 조건문 처리해보려고 합니다.
