### ISSUE TITLE
로그인 방식 변경 건

### ISSUE THREAD

**Issue by KKHoon210417** [hellonayeon/recipe-recommend-service#63]
로그인 방식 변경건 이슈 올립니다.

일안) username을 로그인 id로 사용하고 이메일은 수집만하자
이안) mongodb고유의 id값을 이용해 로그인 id로 이용하자

추가로 의견있으면 댓글 남겨주세용

**Comment by profoundsea25** [comment]
죄송하지만 제가 기억이 안 나서 그런데 로그인 방식을 변경하는 이유가 무엇인가요?
 
<details markdown="1">
<summary>이유를 잘 모르는 상태지만 제 의견</summary>
<br>

현재 사용자 식별 역할을 할 수 있는 변수가 mongoDB user 시트 기준
- mongoDB 고유 _id값
- username
- email
- profile_name

이렇게 4가지인데, 저는 
- 지금처럼 email로 로그인하고, 
- 지금처럼 닉네임 기능은 username을 활용하고, 
- _id는 활용하지 않고, profile_name은 삭제하는 것이 어떤가 싶습니다.

참고로 현재 제가 구현한 좋아요 기능은 email을 통해 DB에서 정보를 가져오고, username으로 이용자를 식별하고 있습니다.
반드시 바꿔야만 하는 이유가 있지 않다면 현재 방식을 그대로 유지하고 profile_name은 삭제해도 무방하지 않나요?
</details>

**Comment by hellonayeon** [comment]
지금 저희가 설계해놓은 데이터베이스는 사용자를 `email`로도 식별이 가능하고 `username`으로도 식별이 가능한 상태입니다.
그러니 저희 `데이터베이스 user 컬렉션`은 `primary key` 가 2개인 상태네요. `email` `username` 각각 개별적으로 사용해서 사용자 레코드 식별이 가능하다면 둘 중에 하나는 `key`의 역할을 하지 않도록 하는 것이 좋다고 생각합니다.

해준님 말씀처럼
> 참고로 현재 제가 구현한 좋아요 기능은 email을 통해 DB에서 정보를 가져오고, username으로 이용자를 식별하고 있습니다.

`email`을 `key`로 사용하는 것도 좋지만, 다른 API를 설계할때 `email`이 `key`로서 사용된다면
광훈님이 구현하신 마이페이지의 API의 경우 `/user/abc@abc.com` 이런식으로 요청을 보내게 됩니다. 

뿐만 아니라 `key`가 두개가 된다면 어떤 사람은 데이터베이스에서 값을 가져오기 위해 `email`을 사용하고, 또 다른 사람은 `username`을 사용한다면, 나중에 다른 팀원들과 코드 리뷰를 하는 경우나 다른 사람이 그 기능을 맡게된 경우에 혼란을 주게될 것입니다.

그래서 제가 저번에 이메일은 사용자의 `추가적인 정보` 로서의 데이터로 가져가고 사용자를 식별하는 `ID`를 다시 정의하는게 좋겠다고 말씀드린겁니다!

**Comment by hellonayeon** [comment]
`데이터베이스 primary key` 와 관련한 글 하나 첨부합니다~~
https://jhnyang.tistory.com/71

**Comment by hellonayeon** [comment]
해준님 말씀대로 **유저 식별 기능을 `_id`로 사용**한다면 `좋아요` 기능 구현 시 데이터 관리하기 수월할 것 같네요!

마이페이지 API의 경우에는 `/user/615fb88da2d7102ae1cbcaae` URL로 요청을 보낼 수 있어, 사용자의 민감한 정보가 노출되지 않으니 이 부분에서도 문제가 없을 듯 합니다.

그럼 제가 로그인 시 토큰을 발급하는 부분에서 사용자 데이터에 해당하는 `_id` 값을 가져와서 토큰에 저장해둬야겠네요.

저는 해준님 의견에 동의합니다. 제가 맡은 로그인 기능에 있어서 이 방식으로 변경하는데 문제 없을 것 같아요! 다른 팀원분들 의견도 들어보고 제가 수정해야할 부분에 대해 이슈 올려놓겠습니다.

**해준님의 의견에 있어서 제가 동의한 부분 정리 **
* 로그인 과정을 **이메일**로 처리
* 로그인 이후 사용자와 관련해서 처리하는 기능들은 `_id` 값으로 사용자 식별

** username의 사용에 대한 제 의견 **
그럼 `username`은 저희가 카카오톡 프로필 이름을 맘대로 중복 걱정 없이 마음대로 바꿀 수 있듯, `key`로서의 역할을 하는 데이터가 아닌 사용자가 자유롭게 변경할 수 있는 데이터로 남기는게 어떨까 싶네요. 그럼 따로 `profile_name` 이라는 필드를 관리하지 않아도 되고, 좋아요 기능에서 사용자 이름이 변경됨에따라 데이터를 수정해야하는 일을 하지 않아도 되니, 구현의 많은 부분에 있어서 혼동을 피할 수 있을 것 같습니다!

이 부분에 대해 저번주에 의견이 나왔으나 정리가 안된 상태였는데, 광훈님이 이슈로 정리 해주시고, 해준님이 한번 더 짚어주셔서 정확하게 해결하고 다음주 구현 들어갈 수 있게 됐네요. 두 분다 이 문제에 대해 깊게 고민해주셔서 감사합니다 👍

---

저희가 코드 작성 경험이 많고 서비스를 많이 만들어봤다면 개발에 들어가기 전 설계 단계에서 이런 문제들까지 생각해서 정확하게 틀을 짜놓고 구현을 할 수 있었을겁니다. 하지만 모두 배우는 단계이고 이제 경험을 하는 단계이기 때문에 힘들게 구현을 했지만 수정해야하는 경우도 있고 최악의 경우 다 만들어 놓은 기능을 갈아 엎어버려야하는 상황도 발생 할 수 있습니다🤣 그런 상황이 닥치게 됐을때 수고스럽기도 하고 속상하기도 하지만, 더 타당한 비즈니스 로직을 구현할수 있고 또 좋은 서비스로 개선할 수 있다고 생각하면 전혀 주저할 일은 아니라고 생각합니다. 제가 팀장으로서 설계 부분에서 정확하게 리드를 못해드린 것 같아 죄송한 마음이네요.. 저도 많이 부족하지만 앞으로 이런 비슷한 이슈에 관련해서는 초반에 설계 단계에서 문제를 여러 방면으로 생각해보고 여러분들과 다양한 방법들에 대해 논의할 수 있도록 노력하겠습니다! 이번을 기회삼아 초기 설계의 중요성을 깨닫고, 처음이라 어렵겠지만 앞으로는 기능 구현 전에 내부적으로 어떻게 동작할지 까지 생각해가며 충분한 설계 시간을 가져가도록 같이 노력해봅시다!

**Comment by hellonayeon** [comment]
`username`이 `프로필 이름`과 `댓글 작성` `레시피 등록` 시 사용하게 될텐데 `username` 중복 검사를 하는게 좋겠다는 생각이 드네요.. 여러분들 의견은 어떠신가요??

`디스코드` 앱 같은 경우 사용자 이름 중복을 허용하고 `사용자 코드` 를 따로 표시하는 것 처럼 가도 될거같네요.
`AWS`의 경우에도 `사용자 이름`외에 `AWS 계정 아이디`가 따로 있는 것을 보니 이름 중복을 허용하고 `계정 ID`로 사용자를 구분하는 것 같아요.

**Comment by hellonayeon** [comment]
**방법1**
로그인: email / 로그인 용도 / 중복 검사해서 변경 가능
내부적으로 사용자 식별: _id
서비스 상에서 보여지는 사용자 이름: username / 자유롭게 변경가능

**방법2**
로그인: username / 로그인 용도 / 변경 불가능
내부적으로 사용자 식별: username
서비스 상에서 보여지는 사용자 이름: profile_name

**Comment by hellonayeon** [comment]
방법1 로 가겠습니다~~

**방법1**
로그인: email / 로그인 용도 / 중복 검사해서 변경 가능
내부적으로 사용자 식별: _id
서비스 상에서 보여지는 사용자 이름: username / 자유롭게 변경가능 / 마이페이지 프로필 이름으로 사용 / 댓글 기능에서 사용

---

**동일한 username을 가진 사용자는 어떻게 구분하나**
`username(_id)` 로 구분하도록 명시해주기 https://github.com/hellonayeon/recipe-recommend-service/issues/63#issuecomment-939501036
