### ISSUE TITLE
마이페이지 개선 : 레시피 검색 기능, 자세히 보기 기능 활성화

### ISSUE THREAD

**Issue by profoundsea25** [hellonayeon/recipe-recommend-service#76]
- [x] 자세히 보기 기능 활성화 - 상세페이지 분리 필요
- [x] 레시피 검색 기능 활성화 - 페이지 분리 필요

html과 url이 달라, 같은 기능을 페이지에 맞게 수정해야 합니다.
마이페이지 수정과 함께 제가 하겠습니다.

**Comment by hellonayeon** [comment]
`마이페이지` 에서 `레시피 검색` 기능 수행시, 페이지가 의도대로 안넘어가는 문제 발생

**예상 원인**
* `/` 로 리다이렉션 되버리기 때문에 `window.location.replace` 이후 구문이 실행이 안된다(?)
|__ `$document.ready()` 실행되면서 `showController()` 가 의도대로 동작 안해서(?)

**가능한 해결 방법**
1) 마이페이지 검색란을 숨기기
2) 재료 검색 영역과 레시피 리스트 출력 영역을 합치기
3) 재료 검색 페이지 / 레시피 리스트 페이지 나누기

현재 상태(`show hide`)에서 계속 해결해보시고 안되시면 말씀해주시기로 했습니다.

**Comment by hellonayeon** [comment]
상세페이지 분리했습니다! 커밋 `cbea4cc`
