### ISSUE TITLE
EB 환경 재구축

### ISSUE THREAD

**Issue by hellonayeon** [hellonayeon/recipe-recommend-service#87]
😢

**Comment by profoundsea25** [comment]
😢

**Comment by hellonayeon** [comment]
**문제 상황**
재배포 시 기존에 업로드한 이미지들이 증발
|__ S3 버킷에서 EB 버전 내용을 확인해보니, 프로젝트 폴더의 내용을 새로 올려놓는거라 기존에 저장된 이미지들 삭제


**해결 방법**
1) MongoDB를 설치해놓은 EC2에 파일들을 저장한다.
2) S3에 파일들을 저장한다.

2안으로 해볼 생각입니다.


**해결 과정**
1) boto3 로 S3 작업 코드 작성: **파일 저장하기 / 파일 가져오기**
2) EB 구성 환경변수 및 Github Action Secret 추가 ["BUCKET_NAME"]
